### ISSUE TITLE
Les moteurs de recherche de documents ne marche pas

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyDocClient#2]
Aucun moteur de recherche ne fonctionne (ni au niveau de la page de liste de documents, ni dans la fenêtre de liens internes)

**Comment by neoxium** [comment]
Corrigé sur le serveur, suppression de MySQL et installation de MariaDB (SQL_MODE ONLY_FULL_GROUP_BY incompatible avec Knp Paginator)
