### ISSUE TITLE
Invitation de nouveaux utilisateurs

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyDocClient#25]
On comprends pas le mail. Et on sait pas quoi faire. Le lien renvoie vers le log et donc ? 

Ca devrait tester si l'utilisateur existe déjà et si y’a un mot de passe. Si mail et pas de mot de passe >>> une page de "bienvenu" avec création de mot de passe (avec double entrée de mots de passe et vérification) puis arrivé vers la page de base.

**Comment by neoxium** [comment]
Mot de passe envoyé dans l'invitation si l'utilisateur a été créé.
