### ISSUE TITLE
Ajouter un lien interne - problème de lien

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyDocClient#3]
Dans la fenêtre contextuelle d'ajout de notation dans l'onglet "lien interne", le lien vers le document bascule vers le nouveau document ce qui est trompeur. Il faut que se lien soit redondant avec le lien lier (qui devrait être un bouton bleu) pour ajouter le lien interne sur le document de travail

**Comment by neoxium** [comment]
Fixed in c98cdefbbee0fe533c5f519ec4ee184d03e55020
