### ISSUE TITLE
Guillet dans les metas ca bug

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyDocClient#9]
Guillemets : La gestion des guillemets dans les guillemets fait tout sauter dans les méta (voir dans le corps) donc il faut un contrôleur de guillemet dans les méta qui les transforme à la volée tous en guillemet simple

**Comment by neoxium** [comment]
Ce n'est pas un bug, il faut respecter le format YAML

**Comment by neoxium** [comment]
Improved in 66e8f3b90ea2da76b6797f90d4f75cf4821c2ca8
